//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v13.15.10.0 (NJsonSchema v10.6.10.0 (Newtonsoft.Json v12.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

#pragma warning disable 108 // Disable "CS0108 '{derivedDto}.ToJson()' hides inherited member '{dtoBase}.ToJson()'. Use the new keyword if hiding was intended."
#pragma warning disable 114 // Disable "CS0114 '{derivedDto}.RaisePropertyChanged(String)' hides inherited member 'dtoBase.RaisePropertyChanged(String)'. To make the current member override that implementation, add the override keyword. Otherwise add the new keyword."
#pragma warning disable 472 // Disable "CS0472 The result of the expression is always 'false' since a value of type 'Int32' is never equal to 'null' of type 'Int32?'
#pragma warning disable 1573 // Disable "CS1573 Parameter '...' has no matching param tag in the XML comment for ...
#pragma warning disable 1591 // Disable "CS1591 Missing XML comment for publicly visible type or member ..."
#pragma warning disable 8073 // Disable "CS8073 The result of the expression is always 'false' since a value of type 'T' is never equal to 'null' of type 'T?'"
#pragma warning disable 3016 // Disable "CS3016 Arrays as attribute arguments is not CLS-compliant"
#pragma warning disable 8603 // Disable "CS8603 Possible null reference return"

namespace MetricsManager.Client
{
    using System = global::System;

    [System.CodeDom.Compiler.GeneratedCode("NSwag", "13.15.10.0 (NJsonSchema v10.6.10.0 (Newtonsoft.Json v12.0.0.0))")]
    public partial interface IMetricsAgentClient
    {
        /// <summary>
        /// Получает метрики CPU (использования процессора) на заданном диапазоне времени
        /// </summary>
        /// <param name="fromTime">начальная метрика времени в секундах с 01.01.1970</param>
        /// <param name="toTime">конечная метрика времени в секундах с 01.01.1970</param>
        /// <returns>Если всё хорошо</returns>
        /// <exception cref="ApiException">A server side error occurred.</exception>
        System.Threading.Tasks.Task ApiMetricsCpuFromToAsync(TimeSpan fromTime, TimeSpan toTime);

        /// <summary>
        /// Получает метрики CPU (использования процессора) на заданном диапазоне времени
        /// </summary>
        /// <param name="fromTime">начальная метрика времени в секундах с 01.01.1970</param>
        /// <param name="toTime">конечная метрика времени в секундах с 01.01.1970</param>
        /// <returns>Если всё хорошо</returns>
        /// <exception cref="ApiException">A server side error occurred.</exception>
        void ApiMetricsCpuFromTo(TimeSpan fromTime, TimeSpan toTime);

        /// <param name="cancellationToken">A cancellation token that can be used by other objects or threads to receive notice of cancellation.</param>
        /// <summary>
        /// Получает метрики CPU (использования процессора) на заданном диапазоне времени
        /// </summary>
        /// <param name="fromTime">начальная метрика времени в секундах с 01.01.1970</param>
        /// <param name="toTime">конечная метрика времени в секундах с 01.01.1970</param>
        /// <returns>Если всё хорошо</returns>
        /// <exception cref="ApiException">A server side error occurred.</exception>
        System.Threading.Tasks.Task ApiMetricsCpuFromToAsync(TimeSpan fromTime, TimeSpan toTime, System.Threading.CancellationToken cancellationToken);

        /// <summary>
        /// Получает метрики DotNet (количество ошибок .NET) на заданном диапазоне времени
        /// </summary>
        /// <param name="fromTime">начальная метрика времени в секундах с 01.01.1970</param>
        /// <param name="toTime">конечная метрика времени в секундах с 01.01.1970</param>
        /// <returns>Если всё хорошо</returns>
        /// <exception cref="ApiException">A server side error occurred.</exception>
        System.Threading.Tasks.Task ApiMetricsDotnetErrorsCountFromToAsync(TimeSpan fromTime, TimeSpan toTime);

        /// <summary>
        /// Получает метрики DotNet (количество ошибок .NET) на заданном диапазоне времени
        /// </summary>
        /// <param name="fromTime">начальная метрика времени в секундах с 01.01.1970</param>
        /// <param name="toTime">конечная метрика времени в секундах с 01.01.1970</param>
        /// <returns>Если всё хорошо</returns>
        /// <exception cref="ApiException">A server side error occurred.</exception>
        void ApiMetricsDotnetErrorsCountFromTo(TimeSpan fromTime, TimeSpan toTime);

        /// <param name="cancellationToken">A cancellation token that can be used by other objects or threads to receive notice of cancellation.</param>
        /// <summary>
        /// Получает метрики DotNet (количество ошибок .NET) на заданном диапазоне времени
        /// </summary>
        /// <param name="fromTime">начальная метрика времени в секундах с 01.01.1970</param>
        /// <param name="toTime">конечная метрика времени в секундах с 01.01.1970</param>
        /// <returns>Если всё хорошо</returns>
        /// <exception cref="ApiException">A server side error occurred.</exception>
        System.Threading.Tasks.Task ApiMetricsDotnetErrorsCountFromToAsync(TimeSpan fromTime, TimeSpan toTime, System.Threading.CancellationToken cancellationToken);

        /// <summary>
        /// Получает метрики HDD (свободное пространство на диске C:) на заданном диапазоне времени
        /// </summary>
        /// <param name="fromTime">начальная метрика времени в секундах с 01.01.1970</param>
        /// <param name="toTime">конечная метрика времени в секундах с 01.01.1970</param>
        /// <returns>Если всё хорошо</returns>
        /// <exception cref="ApiException">A server side error occurred.</exception>
        System.Threading.Tasks.Task ApiMetricsHddLeftFromToAsync(TimeSpan fromTime, TimeSpan toTime);

        /// <summary>
        /// Получает метрики HDD (свободное пространство на диске C:) на заданном диапазоне времени
        /// </summary>
        /// <param name="fromTime">начальная метрика времени в секундах с 01.01.1970</param>
        /// <param name="toTime">конечная метрика времени в секундах с 01.01.1970</param>
        /// <returns>Если всё хорошо</returns>
        /// <exception cref="ApiException">A server side error occurred.</exception>
        void ApiMetricsHddLeftFromTo(TimeSpan fromTime, TimeSpan toTime);

        /// <param name="cancellationToken">A cancellation token that can be used by other objects or threads to receive notice of cancellation.</param>
        /// <summary>
        /// Получает метрики HDD (свободное пространство на диске C:) на заданном диапазоне времени
        /// </summary>
        /// <param name="fromTime">начальная метрика времени в секундах с 01.01.1970</param>
        /// <param name="toTime">конечная метрика времени в секундах с 01.01.1970</param>
        /// <returns>Если всё хорошо</returns>
        /// <exception cref="ApiException">A server side error occurred.</exception>
        System.Threading.Tasks.Task ApiMetricsHddLeftFromToAsync(TimeSpan fromTime, TimeSpan toTime, System.Threading.CancellationToken cancellationToken);

        /// <summary>
        /// Получает метрики Network (количество передаваемых дейтаграм по IPv4 в секунду) на заданном диапазоне времени
        /// </summary>
        /// <param name="fromTime">начальная метрика времени в секундах с 01.01.1970</param>
        /// <param name="toTime">конечная метрика времени в секундах с 01.01.1970</param>
        /// <returns>Если всё хорошо</returns>
        /// <exception cref="ApiException">A server side error occurred.</exception>
        System.Threading.Tasks.Task ApiMetricsNetworkFromToAsync(TimeSpan fromTime, TimeSpan toTime);

        /// <summary>
        /// Получает метрики Network (количество передаваемых дейтаграм по IPv4 в секунду) на заданном диапазоне времени
        /// </summary>
        /// <param name="fromTime">начальная метрика времени в секундах с 01.01.1970</param>
        /// <param name="toTime">конечная метрика времени в секундах с 01.01.1970</param>
        /// <returns>Если всё хорошо</returns>
        /// <exception cref="ApiException">A server side error occurred.</exception>
        void ApiMetricsNetworkFromTo(TimeSpan fromTime, TimeSpan toTime);

        /// <param name="cancellationToken">A cancellation token that can be used by other objects or threads to receive notice of cancellation.</param>
        /// <summary>
        /// Получает метрики Network (количество передаваемых дейтаграм по IPv4 в секунду) на заданном диапазоне времени
        /// </summary>
        /// <param name="fromTime">начальная метрика времени в секундах с 01.01.1970</param>
        /// <param name="toTime">конечная метрика времени в секундах с 01.01.1970</param>
        /// <returns>Если всё хорошо</returns>
        /// <exception cref="ApiException">A server side error occurred.</exception>
        System.Threading.Tasks.Task ApiMetricsNetworkFromToAsync(TimeSpan fromTime, TimeSpan toTime, System.Threading.CancellationToken cancellationToken);

        /// <summary>
        /// Получает метрики RAM (объем свободной памяти) на заданном диапазоне времени
        /// </summary>
        /// <param name="fromTime">начальная метрика времени в секундах с 01.01.1970</param>
        /// <param name="toTime">конечная метрика времени в секундах с 01.01.1970</param>
        /// <returns>Если всё хорошо</returns>
        /// <exception cref="ApiException">A server side error occurred.</exception>
        System.Threading.Tasks.Task ApiMetricsRamAvailableFromToAsync(TimeSpan fromTime, TimeSpan toTime);

        /// <summary>
        /// Получает метрики RAM (объем свободной памяти) на заданном диапазоне времени
        /// </summary>
        /// <param name="fromTime">начальная метрика времени в секундах с 01.01.1970</param>
        /// <param name="toTime">конечная метрика времени в секундах с 01.01.1970</param>
        /// <returns>Если всё хорошо</returns>
        /// <exception cref="ApiException">A server side error occurred.</exception>
        void ApiMetricsRamAvailableFromTo(TimeSpan fromTime, TimeSpan toTime);

        /// <param name="cancellationToken">A cancellation token that can be used by other objects or threads to receive notice of cancellation.</param>
        /// <summary>
        /// Получает метрики RAM (объем свободной памяти) на заданном диапазоне времени
        /// </summary>
        /// <param name="fromTime">начальная метрика времени в секундах с 01.01.1970</param>
        /// <param name="toTime">конечная метрика времени в секундах с 01.01.1970</param>
        /// <returns>Если всё хорошо</returns>
        /// <exception cref="ApiException">A server side error occurred.</exception>
        System.Threading.Tasks.Task ApiMetricsRamAvailableFromToAsync(TimeSpan fromTime, TimeSpan toTime, System.Threading.CancellationToken cancellationToken);

    }

    [System.CodeDom.Compiler.GeneratedCode("NSwag", "13.15.10.0 (NJsonSchema v10.6.10.0 (Newtonsoft.Json v12.0.0.0))")]
    public partial class MetricsAgentClient : IMetricsAgentClient
    {
        private string _baseUrl = "";
        private System.Net.Http.HttpClient _httpClient;
        private System.Lazy<Newtonsoft.Json.JsonSerializerSettings> _settings;

        public MetricsAgentClient(string baseUrl, System.Net.Http.HttpClient httpClient)
        {
            BaseUrl = baseUrl;
            _httpClient = httpClient;
            _settings = new System.Lazy<Newtonsoft.Json.JsonSerializerSettings>(CreateSerializerSettings);
        }

        private Newtonsoft.Json.JsonSerializerSettings CreateSerializerSettings()
        {
            var settings = new Newtonsoft.Json.JsonSerializerSettings();
            UpdateJsonSerializerSettings(settings);
            return settings;
        }

        public string BaseUrl
        {
            get { return _baseUrl; }
            set { _baseUrl = value; }
        }

        protected Newtonsoft.Json.JsonSerializerSettings JsonSerializerSettings { get { return _settings.Value; } }

        partial void UpdateJsonSerializerSettings(Newtonsoft.Json.JsonSerializerSettings settings);

        partial void PrepareRequest(System.Net.Http.HttpClient client, System.Net.Http.HttpRequestMessage request, string url);
        partial void PrepareRequest(System.Net.Http.HttpClient client, System.Net.Http.HttpRequestMessage request, System.Text.StringBuilder urlBuilder);
        partial void ProcessResponse(System.Net.Http.HttpClient client, System.Net.Http.HttpResponseMessage response);

        /// <summary>
        /// Получает метрики CPU (использования процессора) на заданном диапазоне времени
        /// </summary>
        /// <param name="fromTime">начальная метрика времени в секундах с 01.01.1970</param>
        /// <param name="toTime">конечная метрика времени в секундах с 01.01.1970</param>
        /// <returns>Если всё хорошо</returns>
        /// <exception cref="ApiException">A server side error occurred.</exception>
        public virtual System.Threading.Tasks.Task ApiMetricsCpuFromToAsync(TimeSpan fromTime, TimeSpan toTime)
        {
            return ApiMetricsCpuFromToAsync(fromTime, toTime, System.Threading.CancellationToken.None);
        }

        /// <summary>
        /// Получает метрики CPU (использования процессора) на заданном диапазоне времени
        /// </summary>
        /// <param name="fromTime">начальная метрика времени в секундах с 01.01.1970</param>
        /// <param name="toTime">конечная метрика времени в секундах с 01.01.1970</param>
        /// <returns>Если всё хорошо</returns>
        /// <exception cref="ApiException">A server side error occurred.</exception>
        public virtual void ApiMetricsCpuFromTo(TimeSpan fromTime, TimeSpan toTime)
        {
            System.Threading.Tasks.Task.Run(async () => await ApiMetricsCpuFromToAsync(fromTime, toTime, System.Threading.CancellationToken.None)).GetAwaiter().GetResult();
        }

        /// <param name="cancellationToken">A cancellation token that can be used by other objects or threads to receive notice of cancellation.</param>
        /// <summary>
        /// Получает метрики CPU (использования процессора) на заданном диапазоне времени
        /// </summary>
        /// <param name="fromTime">начальная метрика времени в секундах с 01.01.1970</param>
        /// <param name="toTime">конечная метрика времени в секундах с 01.01.1970</param>
        /// <returns>Если всё хорошо</returns>
        /// <exception cref="ApiException">A server side error occurred.</exception>
        public virtual async System.Threading.Tasks.Task ApiMetricsCpuFromToAsync(TimeSpan fromTime, TimeSpan toTime, System.Threading.CancellationToken cancellationToken)
        {
            if (fromTime == null)
                throw new System.ArgumentNullException("fromTime");

            if (toTime == null)
                throw new System.ArgumentNullException("toTime");

            var urlBuilder_ = new System.Text.StringBuilder();
            urlBuilder_.Append(BaseUrl != null ? BaseUrl.TrimEnd('/') : "").Append("/api/metrics/cpu/from/{fromTime}/to/{toTime}");
            urlBuilder_.Replace("{fromTime}", System.Uri.EscapeDataString(ConvertToString(fromTime, System.Globalization.CultureInfo.InvariantCulture)));
            urlBuilder_.Replace("{toTime}", System.Uri.EscapeDataString(ConvertToString(toTime, System.Globalization.CultureInfo.InvariantCulture)));

            var client_ = _httpClient;
            var disposeClient_ = false;
            try
            {
                using (var request_ = new System.Net.Http.HttpRequestMessage())
                {
                    request_.Method = new System.Net.Http.HttpMethod("GET");

                    PrepareRequest(client_, request_, urlBuilder_);

                    var url_ = urlBuilder_.ToString();
                    request_.RequestUri = new System.Uri(url_, System.UriKind.RelativeOrAbsolute);

                    PrepareRequest(client_, request_, url_);

                    var response_ = await client_.SendAsync(request_, System.Net.Http.HttpCompletionOption.ResponseHeadersRead, cancellationToken).ConfigureAwait(false);
                    var disposeResponse_ = true;
                    try
                    {
                        var headers_ = System.Linq.Enumerable.ToDictionary(response_.Headers, h_ => h_.Key, h_ => h_.Value);
                        if (response_.Content != null && response_.Content.Headers != null)
                        {
                            foreach (var item_ in response_.Content.Headers)
                                headers_[item_.Key] = item_.Value;
                        }

                        ProcessResponse(client_, response_);

                        var status_ = (int)response_.StatusCode;
                        if (status_ == 200)
                        {
                            return;
                        }
                        else
                        if (status_ == 400)
                        {
                            string responseText_ = ( response_.Content == null ) ? string.Empty : await response_.Content.ReadAsStringAsync().ConfigureAwait(false);
                            throw new ApiException("\u0415\u0441\u043b\u0438 \u043f\u0435\u0440\u0435\u0434\u0430\u043b\u0438 \u043d\u0435\u043f\u0440\u0430\u0432\u0438\u043b\u044c\u043d\u044b\u0435 \u043f\u0430\u0440\u0430\u043c\u0435\u0442\u0440\u044b", status_, responseText_, headers_, null);
                        }
                        else
                        {
                            var responseData_ = response_.Content == null ? null : await response_.Content.ReadAsStringAsync().ConfigureAwait(false);
                            throw new ApiException("The HTTP status code of the response was not expected (" + status_ + ").", status_, responseData_, headers_, null);
                        }
                    }
                    finally
                    {
                        if (disposeResponse_)
                            response_.Dispose();
                    }
                }
            }
            finally
            {
                if (disposeClient_)
                    client_.Dispose();
            }
        }

        /// <summary>
        /// Получает метрики DotNet (количество ошибок .NET) на заданном диапазоне времени
        /// </summary>
        /// <param name="fromTime">начальная метрика времени в секундах с 01.01.1970</param>
        /// <param name="toTime">конечная метрика времени в секундах с 01.01.1970</param>
        /// <returns>Если всё хорошо</returns>
        /// <exception cref="ApiException">A server side error occurred.</exception>
        public virtual System.Threading.Tasks.Task ApiMetricsDotnetErrorsCountFromToAsync(TimeSpan fromTime, TimeSpan toTime)
        {
            return ApiMetricsDotnetErrorsCountFromToAsync(fromTime, toTime, System.Threading.CancellationToken.None);
        }

        /// <summary>
        /// Получает метрики DotNet (количество ошибок .NET) на заданном диапазоне времени
        /// </summary>
        /// <param name="fromTime">начальная метрика времени в секундах с 01.01.1970</param>
        /// <param name="toTime">конечная метрика времени в секундах с 01.01.1970</param>
        /// <returns>Если всё хорошо</returns>
        /// <exception cref="ApiException">A server side error occurred.</exception>
        public virtual void ApiMetricsDotnetErrorsCountFromTo(TimeSpan fromTime, TimeSpan toTime)
        {
            System.Threading.Tasks.Task.Run(async () => await ApiMetricsDotnetErrorsCountFromToAsync(fromTime, toTime, System.Threading.CancellationToken.None)).GetAwaiter().GetResult();
        }

        /// <param name="cancellationToken">A cancellation token that can be used by other objects or threads to receive notice of cancellation.</param>
        /// <summary>
        /// Получает метрики DotNet (количество ошибок .NET) на заданном диапазоне времени
        /// </summary>
        /// <param name="fromTime">начальная метрика времени в секундах с 01.01.1970</param>
        /// <param name="toTime">конечная метрика времени в секундах с 01.01.1970</param>
        /// <returns>Если всё хорошо</returns>
        /// <exception cref="ApiException">A server side error occurred.</exception>
        public virtual async System.Threading.Tasks.Task ApiMetricsDotnetErrorsCountFromToAsync(TimeSpan fromTime, TimeSpan toTime, System.Threading.CancellationToken cancellationToken)
        {
            if (fromTime == null)
                throw new System.ArgumentNullException("fromTime");

            if (toTime == null)
                throw new System.ArgumentNullException("toTime");

            var urlBuilder_ = new System.Text.StringBuilder();
            urlBuilder_.Append(BaseUrl != null ? BaseUrl.TrimEnd('/') : "").Append("/api/metrics/dotnet/errors-count/from/{fromTime}/to/{toTime}");
            urlBuilder_.Replace("{fromTime}", System.Uri.EscapeDataString(ConvertToString(fromTime, System.Globalization.CultureInfo.InvariantCulture)));
            urlBuilder_.Replace("{toTime}", System.Uri.EscapeDataString(ConvertToString(toTime, System.Globalization.CultureInfo.InvariantCulture)));

            var client_ = _httpClient;
            var disposeClient_ = false;
            try
            {
                using (var request_ = new System.Net.Http.HttpRequestMessage())
                {
                    request_.Method = new System.Net.Http.HttpMethod("GET");

                    PrepareRequest(client_, request_, urlBuilder_);

                    var url_ = urlBuilder_.ToString();
                    request_.RequestUri = new System.Uri(url_, System.UriKind.RelativeOrAbsolute);

                    PrepareRequest(client_, request_, url_);

                    var response_ = await client_.SendAsync(request_, System.Net.Http.HttpCompletionOption.ResponseHeadersRead, cancellationToken).ConfigureAwait(false);
                    var disposeResponse_ = true;
                    try
                    {
                        var headers_ = System.Linq.Enumerable.ToDictionary(response_.Headers, h_ => h_.Key, h_ => h_.Value);
                        if (response_.Content != null && response_.Content.Headers != null)
                        {
                            foreach (var item_ in response_.Content.Headers)
                                headers_[item_.Key] = item_.Value;
                        }

                        ProcessResponse(client_, response_);

                        var status_ = (int)response_.StatusCode;
                        if (status_ == 200)
                        {
                            return;
                        }
                        else
                        if (status_ == 400)
                        {
                            string responseText_ = ( response_.Content == null ) ? string.Empty : await response_.Content.ReadAsStringAsync().ConfigureAwait(false);
                            throw new ApiException("\u0415\u0441\u043b\u0438 \u043f\u0435\u0440\u0435\u0434\u0430\u043b\u0438 \u043d\u0435\u043f\u0440\u0430\u0432\u0438\u043b\u044c\u043d\u044b\u0435 \u043f\u0430\u0440\u0430\u043c\u0435\u0442\u0440\u044b", status_, responseText_, headers_, null);
                        }
                        else
                        {
                            var responseData_ = response_.Content == null ? null : await response_.Content.ReadAsStringAsync().ConfigureAwait(false);
                            throw new ApiException("The HTTP status code of the response was not expected (" + status_ + ").", status_, responseData_, headers_, null);
                        }
                    }
                    finally
                    {
                        if (disposeResponse_)
                            response_.Dispose();
                    }
                }
            }
            finally
            {
                if (disposeClient_)
                    client_.Dispose();
            }
        }

        /// <summary>
        /// Получает метрики HDD (свободное пространство на диске C:) на заданном диапазоне времени
        /// </summary>
        /// <param name="fromTime">начальная метрика времени в секундах с 01.01.1970</param>
        /// <param name="toTime">конечная метрика времени в секундах с 01.01.1970</param>
        /// <returns>Если всё хорошо</returns>
        /// <exception cref="ApiException">A server side error occurred.</exception>
        public virtual System.Threading.Tasks.Task ApiMetricsHddLeftFromToAsync(TimeSpan fromTime, TimeSpan toTime)
        {
            return ApiMetricsHddLeftFromToAsync(fromTime, toTime, System.Threading.CancellationToken.None);
        }

        /// <summary>
        /// Получает метрики HDD (свободное пространство на диске C:) на заданном диапазоне времени
        /// </summary>
        /// <param name="fromTime">начальная метрика времени в секундах с 01.01.1970</param>
        /// <param name="toTime">конечная метрика времени в секундах с 01.01.1970</param>
        /// <returns>Если всё хорошо</returns>
        /// <exception cref="ApiException">A server side error occurred.</exception>
        public virtual void ApiMetricsHddLeftFromTo(TimeSpan fromTime, TimeSpan toTime)
        {
            System.Threading.Tasks.Task.Run(async () => await ApiMetricsHddLeftFromToAsync(fromTime, toTime, System.Threading.CancellationToken.None)).GetAwaiter().GetResult();
        }

        /// <param name="cancellationToken">A cancellation token that can be used by other objects or threads to receive notice of cancellation.</param>
        /// <summary>
        /// Получает метрики HDD (свободное пространство на диске C:) на заданном диапазоне времени
        /// </summary>
        /// <param name="fromTime">начальная метрика времени в секундах с 01.01.1970</param>
        /// <param name="toTime">конечная метрика времени в секундах с 01.01.1970</param>
        /// <returns>Если всё хорошо</returns>
        /// <exception cref="ApiException">A server side error occurred.</exception>
        public virtual async System.Threading.Tasks.Task ApiMetricsHddLeftFromToAsync(TimeSpan fromTime, TimeSpan toTime, System.Threading.CancellationToken cancellationToken)
        {
            if (fromTime == null)
                throw new System.ArgumentNullException("fromTime");

            if (toTime == null)
                throw new System.ArgumentNullException("toTime");

            var urlBuilder_ = new System.Text.StringBuilder();
            urlBuilder_.Append(BaseUrl != null ? BaseUrl.TrimEnd('/') : "").Append("/api/metrics/hdd/left/from/{fromTime}/to/{toTime}");
            urlBuilder_.Replace("{fromTime}", System.Uri.EscapeDataString(ConvertToString(fromTime, System.Globalization.CultureInfo.InvariantCulture)));
            urlBuilder_.Replace("{toTime}", System.Uri.EscapeDataString(ConvertToString(toTime, System.Globalization.CultureInfo.InvariantCulture)));

            var client_ = _httpClient;
            var disposeClient_ = false;
            try
            {
                using (var request_ = new System.Net.Http.HttpRequestMessage())
                {
                    request_.Method = new System.Net.Http.HttpMethod("GET");

                    PrepareRequest(client_, request_, urlBuilder_);

                    var url_ = urlBuilder_.ToString();
                    request_.RequestUri = new System.Uri(url_, System.UriKind.RelativeOrAbsolute);

                    PrepareRequest(client_, request_, url_);

                    var response_ = await client_.SendAsync(request_, System.Net.Http.HttpCompletionOption.ResponseHeadersRead, cancellationToken).ConfigureAwait(false);
                    var disposeResponse_ = true;
                    try
                    {
                        var headers_ = System.Linq.Enumerable.ToDictionary(response_.Headers, h_ => h_.Key, h_ => h_.Value);
                        if (response_.Content != null && response_.Content.Headers != null)
                        {
                            foreach (var item_ in response_.Content.Headers)
                                headers_[item_.Key] = item_.Value;
                        }

                        ProcessResponse(client_, response_);

                        var status_ = (int)response_.StatusCode;
                        if (status_ == 200)
                        {
                            return;
                        }
                        else
                        if (status_ == 400)
                        {
                            string responseText_ = ( response_.Content == null ) ? string.Empty : await response_.Content.ReadAsStringAsync().ConfigureAwait(false);
                            throw new ApiException("\u0415\u0441\u043b\u0438 \u043f\u0435\u0440\u0435\u0434\u0430\u043b\u0438 \u043d\u0435\u043f\u0440\u0430\u0432\u0438\u043b\u044c\u043d\u044b\u0435 \u043f\u0430\u0440\u0430\u043c\u0435\u0442\u0440\u044b", status_, responseText_, headers_, null);
                        }
                        else
                        {
                            var responseData_ = response_.Content == null ? null : await response_.Content.ReadAsStringAsync().ConfigureAwait(false);
                            throw new ApiException("The HTTP status code of the response was not expected (" + status_ + ").", status_, responseData_, headers_, null);
                        }
                    }
                    finally
                    {
                        if (disposeResponse_)
                            response_.Dispose();
                    }
                }
            }
            finally
            {
                if (disposeClient_)
                    client_.Dispose();
            }
        }

        /// <summary>
        /// Получает метрики Network (количество передаваемых дейтаграм по IPv4 в секунду) на заданном диапазоне времени
        /// </summary>
        /// <param name="fromTime">начальная метрика времени в секундах с 01.01.1970</param>
        /// <param name="toTime">конечная метрика времени в секундах с 01.01.1970</param>
        /// <returns>Если всё хорошо</returns>
        /// <exception cref="ApiException">A server side error occurred.</exception>
        public virtual System.Threading.Tasks.Task ApiMetricsNetworkFromToAsync(TimeSpan fromTime, TimeSpan toTime)
        {
            return ApiMetricsNetworkFromToAsync(fromTime, toTime, System.Threading.CancellationToken.None);
        }

        /// <summary>
        /// Получает метрики Network (количество передаваемых дейтаграм по IPv4 в секунду) на заданном диапазоне времени
        /// </summary>
        /// <param name="fromTime">начальная метрика времени в секундах с 01.01.1970</param>
        /// <param name="toTime">конечная метрика времени в секундах с 01.01.1970</param>
        /// <returns>Если всё хорошо</returns>
        /// <exception cref="ApiException">A server side error occurred.</exception>
        public virtual void ApiMetricsNetworkFromTo(TimeSpan fromTime, TimeSpan toTime)
        {
            System.Threading.Tasks.Task.Run(async () => await ApiMetricsNetworkFromToAsync(fromTime, toTime, System.Threading.CancellationToken.None)).GetAwaiter().GetResult();
        }

        /// <param name="cancellationToken">A cancellation token that can be used by other objects or threads to receive notice of cancellation.</param>
        /// <summary>
        /// Получает метрики Network (количество передаваемых дейтаграм по IPv4 в секунду) на заданном диапазоне времени
        /// </summary>
        /// <param name="fromTime">начальная метрика времени в секундах с 01.01.1970</param>
        /// <param name="toTime">конечная метрика времени в секундах с 01.01.1970</param>
        /// <returns>Если всё хорошо</returns>
        /// <exception cref="ApiException">A server side error occurred.</exception>
        public virtual async System.Threading.Tasks.Task ApiMetricsNetworkFromToAsync(TimeSpan fromTime, TimeSpan toTime, System.Threading.CancellationToken cancellationToken)
        {
            if (fromTime == null)
                throw new System.ArgumentNullException("fromTime");

            if (toTime == null)
                throw new System.ArgumentNullException("toTime");

            var urlBuilder_ = new System.Text.StringBuilder();
            urlBuilder_.Append(BaseUrl != null ? BaseUrl.TrimEnd('/') : "").Append("/api/metrics/network/from/{fromTime}/to/{toTime}");
            urlBuilder_.Replace("{fromTime}", System.Uri.EscapeDataString(ConvertToString(fromTime, System.Globalization.CultureInfo.InvariantCulture)));
            urlBuilder_.Replace("{toTime}", System.Uri.EscapeDataString(ConvertToString(toTime, System.Globalization.CultureInfo.InvariantCulture)));

            var client_ = _httpClient;
            var disposeClient_ = false;
            try
            {
                using (var request_ = new System.Net.Http.HttpRequestMessage())
                {
                    request_.Method = new System.Net.Http.HttpMethod("GET");

                    PrepareRequest(client_, request_, urlBuilder_);

                    var url_ = urlBuilder_.ToString();
                    request_.RequestUri = new System.Uri(url_, System.UriKind.RelativeOrAbsolute);

                    PrepareRequest(client_, request_, url_);

                    var response_ = await client_.SendAsync(request_, System.Net.Http.HttpCompletionOption.ResponseHeadersRead, cancellationToken).ConfigureAwait(false);
                    var disposeResponse_ = true;
                    try
                    {
                        var headers_ = System.Linq.Enumerable.ToDictionary(response_.Headers, h_ => h_.Key, h_ => h_.Value);
                        if (response_.Content != null && response_.Content.Headers != null)
                        {
                            foreach (var item_ in response_.Content.Headers)
                                headers_[item_.Key] = item_.Value;
                        }

                        ProcessResponse(client_, response_);

                        var status_ = (int)response_.StatusCode;
                        if (status_ == 200)
                        {
                            return;
                        }
                        else
                        if (status_ == 400)
                        {
                            string responseText_ = ( response_.Content == null ) ? string.Empty : await response_.Content.ReadAsStringAsync().ConfigureAwait(false);
                            throw new ApiException("\u0415\u0441\u043b\u0438 \u043f\u0435\u0440\u0435\u0434\u0430\u043b\u0438 \u043d\u0435\u043f\u0440\u0430\u0432\u0438\u043b\u044c\u043d\u044b\u0435 \u043f\u0430\u0440\u0430\u043c\u0435\u0442\u0440\u044b", status_, responseText_, headers_, null);
                        }
                        else
                        {
                            var responseData_ = response_.Content == null ? null : await response_.Content.ReadAsStringAsync().ConfigureAwait(false);
                            throw new ApiException("The HTTP status code of the response was not expected (" + status_ + ").", status_, responseData_, headers_, null);
                        }
                    }
                    finally
                    {
                        if (disposeResponse_)
                            response_.Dispose();
                    }
                }
            }
            finally
            {
                if (disposeClient_)
                    client_.Dispose();
            }
        }

        /// <summary>
        /// Получает метрики RAM (объем свободной памяти) на заданном диапазоне времени
        /// </summary>
        /// <param name="fromTime">начальная метрика времени в секундах с 01.01.1970</param>
        /// <param name="toTime">конечная метрика времени в секундах с 01.01.1970</param>
        /// <returns>Если всё хорошо</returns>
        /// <exception cref="ApiException">A server side error occurred.</exception>
        public virtual System.Threading.Tasks.Task ApiMetricsRamAvailableFromToAsync(TimeSpan fromTime, TimeSpan toTime)
        {
            return ApiMetricsRamAvailableFromToAsync(fromTime, toTime, System.Threading.CancellationToken.None);
        }

        /// <summary>
        /// Получает метрики RAM (объем свободной памяти) на заданном диапазоне времени
        /// </summary>
        /// <param name="fromTime">начальная метрика времени в секундах с 01.01.1970</param>
        /// <param name="toTime">конечная метрика времени в секундах с 01.01.1970</param>
        /// <returns>Если всё хорошо</returns>
        /// <exception cref="ApiException">A server side error occurred.</exception>
        public virtual void ApiMetricsRamAvailableFromTo(TimeSpan fromTime, TimeSpan toTime)
        {
            System.Threading.Tasks.Task.Run(async () => await ApiMetricsRamAvailableFromToAsync(fromTime, toTime, System.Threading.CancellationToken.None)).GetAwaiter().GetResult();
        }

        /// <param name="cancellationToken">A cancellation token that can be used by other objects or threads to receive notice of cancellation.</param>
        /// <summary>
        /// Получает метрики RAM (объем свободной памяти) на заданном диапазоне времени
        /// </summary>
        /// <param name="fromTime">начальная метрика времени в секундах с 01.01.1970</param>
        /// <param name="toTime">конечная метрика времени в секундах с 01.01.1970</param>
        /// <returns>Если всё хорошо</returns>
        /// <exception cref="ApiException">A server side error occurred.</exception>
        public virtual async System.Threading.Tasks.Task ApiMetricsRamAvailableFromToAsync(TimeSpan fromTime, TimeSpan toTime, System.Threading.CancellationToken cancellationToken)
        {
            if (fromTime == null)
                throw new System.ArgumentNullException("fromTime");

            if (toTime == null)
                throw new System.ArgumentNullException("toTime");

            var urlBuilder_ = new System.Text.StringBuilder();
            urlBuilder_.Append(BaseUrl != null ? BaseUrl.TrimEnd('/') : "").Append("/api/metrics/ram/available/from/{fromTime}/to/{toTime}");
            urlBuilder_.Replace("{fromTime}", System.Uri.EscapeDataString(ConvertToString(fromTime, System.Globalization.CultureInfo.InvariantCulture)));
            urlBuilder_.Replace("{toTime}", System.Uri.EscapeDataString(ConvertToString(toTime, System.Globalization.CultureInfo.InvariantCulture)));

            var client_ = _httpClient;
            var disposeClient_ = false;
            try
            {
                using (var request_ = new System.Net.Http.HttpRequestMessage())
                {
                    request_.Method = new System.Net.Http.HttpMethod("GET");

                    PrepareRequest(client_, request_, urlBuilder_);

                    var url_ = urlBuilder_.ToString();
                    request_.RequestUri = new System.Uri(url_, System.UriKind.RelativeOrAbsolute);

                    PrepareRequest(client_, request_, url_);

                    var response_ = await client_.SendAsync(request_, System.Net.Http.HttpCompletionOption.ResponseHeadersRead, cancellationToken).ConfigureAwait(false);
                    var disposeResponse_ = true;
                    try
                    {
                        var headers_ = System.Linq.Enumerable.ToDictionary(response_.Headers, h_ => h_.Key, h_ => h_.Value);
                        if (response_.Content != null && response_.Content.Headers != null)
                        {
                            foreach (var item_ in response_.Content.Headers)
                                headers_[item_.Key] = item_.Value;
                        }

                        ProcessResponse(client_, response_);

                        var status_ = (int)response_.StatusCode;
                        if (status_ == 200)
                        {
                            return;
                        }
                        else
                        if (status_ == 400)
                        {
                            string responseText_ = ( response_.Content == null ) ? string.Empty : await response_.Content.ReadAsStringAsync().ConfigureAwait(false);
                            throw new ApiException("\u0415\u0441\u043b\u0438 \u043f\u0435\u0440\u0435\u0434\u0430\u043b\u0438 \u043d\u0435\u043f\u0440\u0430\u0432\u0438\u043b\u044c\u043d\u044b\u0435 \u043f\u0430\u0440\u0430\u043c\u0435\u0442\u0440\u044b", status_, responseText_, headers_, null);
                        }
                        else
                        {
                            var responseData_ = response_.Content == null ? null : await response_.Content.ReadAsStringAsync().ConfigureAwait(false);
                            throw new ApiException("The HTTP status code of the response was not expected (" + status_ + ").", status_, responseData_, headers_, null);
                        }
                    }
                    finally
                    {
                        if (disposeResponse_)
                            response_.Dispose();
                    }
                }
            }
            finally
            {
                if (disposeClient_)
                    client_.Dispose();
            }
        }

        protected struct ObjectResponseResult<T>
        {
            public ObjectResponseResult(T responseObject, string responseText)
            {
                this.Object = responseObject;
                this.Text = responseText;
            }

            public T Object { get; }

            public string Text { get; }
        }

        public bool ReadResponseAsString { get; set; }

        protected virtual async System.Threading.Tasks.Task<ObjectResponseResult<T>> ReadObjectResponseAsync<T>(System.Net.Http.HttpResponseMessage response, System.Collections.Generic.IReadOnlyDictionary<string, System.Collections.Generic.IEnumerable<string>> headers, System.Threading.CancellationToken cancellationToken)
        {
            if (response == null || response.Content == null)
            {
                return new ObjectResponseResult<T>(default(T), string.Empty);
            }

            if (ReadResponseAsString)
            {
                var responseText = await response.Content.ReadAsStringAsync().ConfigureAwait(false);
                try
                {
                    var typedBody = Newtonsoft.Json.JsonConvert.DeserializeObject<T>(responseText, JsonSerializerSettings);
                    return new ObjectResponseResult<T>(typedBody, responseText);
                }
                catch (Newtonsoft.Json.JsonException exception)
                {
                    var message = "Could not deserialize the response body string as " + typeof(T).FullName + ".";
                    throw new ApiException(message, (int)response.StatusCode, responseText, headers, exception);
                }
            }
            else
            {
                try
                {
                    using (var responseStream = await response.Content.ReadAsStreamAsync().ConfigureAwait(false))
                    using (var streamReader = new System.IO.StreamReader(responseStream))
                    using (var jsonTextReader = new Newtonsoft.Json.JsonTextReader(streamReader))
                    {
                        var serializer = Newtonsoft.Json.JsonSerializer.Create(JsonSerializerSettings);
                        var typedBody = serializer.Deserialize<T>(jsonTextReader);
                        return new ObjectResponseResult<T>(typedBody, string.Empty);
                    }
                }
                catch (Newtonsoft.Json.JsonException exception)
                {
                    var message = "Could not deserialize the response body stream as " + typeof(T).FullName + ".";
                    throw new ApiException(message, (int)response.StatusCode, string.Empty, headers, exception);
                }
            }
        }

        private string ConvertToString(object value, System.Globalization.CultureInfo cultureInfo)
        {
            if (value == null)
            {
                return "";
            }

            if (value is System.Enum)
            {
                var name = System.Enum.GetName(value.GetType(), value);
                if (name != null)
                {
                    var field = System.Reflection.IntrospectionExtensions.GetTypeInfo(value.GetType()).GetDeclaredField(name);
                    if (field != null)
                    {
                        var attribute = System.Reflection.CustomAttributeExtensions.GetCustomAttribute(field, typeof(System.Runtime.Serialization.EnumMemberAttribute)) 
                            as System.Runtime.Serialization.EnumMemberAttribute;
                        if (attribute != null)
                        {
                            return attribute.Value != null ? attribute.Value : name;
                        }
                    }

                    var converted = System.Convert.ToString(System.Convert.ChangeType(value, System.Enum.GetUnderlyingType(value.GetType()), cultureInfo));
                    return converted == null ? string.Empty : converted;
                }
            }
            else if (value is bool) 
            {
                return System.Convert.ToString((bool)value, cultureInfo).ToLowerInvariant();
            }
            else if (value is byte[])
            {
                return System.Convert.ToBase64String((byte[]) value);
            }
            else if (value.GetType().IsArray)
            {
                var array = System.Linq.Enumerable.OfType<object>((System.Array) value);
                return string.Join(",", System.Linq.Enumerable.Select(array, o => ConvertToString(o, cultureInfo)));
            }

            var result = System.Convert.ToString(value, cultureInfo);
            return result == null ? "" : result;
        }
    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "13.15.10.0 (NJsonSchema v10.6.10.0 (Newtonsoft.Json v12.0.0.0))")]
    public partial class TimeSpan
    {
        [Newtonsoft.Json.JsonProperty("ticks", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public long Ticks { get; set; }

        [Newtonsoft.Json.JsonProperty("days", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public int Days { get; set; }

        [Newtonsoft.Json.JsonProperty("hours", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public int Hours { get; set; }

        [Newtonsoft.Json.JsonProperty("milliseconds", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public int Milliseconds { get; set; }

        [Newtonsoft.Json.JsonProperty("minutes", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public int Minutes { get; set; }

        [Newtonsoft.Json.JsonProperty("seconds", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public int Seconds { get; set; }

        [Newtonsoft.Json.JsonProperty("totalDays", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public double TotalDays { get; set; }

        [Newtonsoft.Json.JsonProperty("totalHours", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public double TotalHours { get; set; }

        [Newtonsoft.Json.JsonProperty("totalMilliseconds", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public double TotalMilliseconds { get; set; }

        [Newtonsoft.Json.JsonProperty("totalMinutes", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public double TotalMinutes { get; set; }

        [Newtonsoft.Json.JsonProperty("totalSeconds", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public double TotalSeconds { get; set; }

    }



    [System.CodeDom.Compiler.GeneratedCode("NSwag", "13.15.10.0 (NJsonSchema v10.6.10.0 (Newtonsoft.Json v12.0.0.0))")]
    public partial class ApiException : System.Exception
    {
        public int StatusCode { get; private set; }

        public string Response { get; private set; }

        public System.Collections.Generic.IReadOnlyDictionary<string, System.Collections.Generic.IEnumerable<string>> Headers { get; private set; }

        public ApiException(string message, int statusCode, string response, System.Collections.Generic.IReadOnlyDictionary<string, System.Collections.Generic.IEnumerable<string>> headers, System.Exception innerException)
            : base(message + "\n\nStatus: " + statusCode + "\nResponse: \n" + ((response == null) ? "(null)" : response.Substring(0, response.Length >= 512 ? 512 : response.Length)), innerException)
        {
            StatusCode = statusCode;
            Response = response;
            Headers = headers;
        }

        public override string ToString()
        {
            return string.Format("HTTP Response: \n\n{0}\n\n{1}", Response, base.ToString());
        }
    }

    [System.CodeDom.Compiler.GeneratedCode("NSwag", "13.15.10.0 (NJsonSchema v10.6.10.0 (Newtonsoft.Json v12.0.0.0))")]
    public partial class ApiException<TResult> : ApiException
    {
        public TResult Result { get; private set; }

        public ApiException(string message, int statusCode, string response, System.Collections.Generic.IReadOnlyDictionary<string, System.Collections.Generic.IEnumerable<string>> headers, TResult result, System.Exception innerException)
            : base(message, statusCode, response, headers, innerException)
        {
            Result = result;
        }
    }

}

#pragma warning restore 1591
#pragma warning restore 1573
#pragma warning restore  472
#pragma warning restore  114
#pragma warning restore  108
#pragma warning restore 3016
#pragma warning restore 8603